[env]
platform = espressif32
board = esp32-c3-devkitm-1
framework = espidf
monitor_speed = 115200

build_flags = 
    -D CONFIG_BT_ENABLED=1
    -D CONFIG_BT_NIMBLE_ENABLED=1
    -D CONFIG_BT_NIMBLE_MAX_CONNECTIONS=1
    -D CONFIG_BT_NIMBLE_SVC_GAP_MIN_OBJ_REGS=1

[env:board_a]
build_flags = ${env.build_flags} -D TARGET_BOARD_A

[env:board_b]
build_flags = ${env.build_flags} -D TARGET_BOARD_B

[env:get_mac]
build_flags = ${env.build_flags} -D DEVICE_GET_MAC