[env]
platform = espressif32
board = esp32-c3-devkitm-1
framework = arduino
monitor_speed = 115200
board_build.partitions = huge_app.csv

[env:board_a]
build_flags = -D TARGET_BOARD_A

[env:board_b]
build_flags = -D TARGET_BOARD_B

[env:get_mac]
build_flags = -D DEVICE_GET_MAC