[env]
platform = espressif32
board = esp32-c3-devkitm-1
framework = arduino
monitor_speed = 115200
board_build.partitions = huge_app.csv

[env:transmitter]
build_flags = -D DEVICE_TRANSMITTER

[env:receiver]
build_flags = -D DEVICE_RECEIVER

[env:get_mac]
build_flags = -D DEVICE_GET_MAC
monitor_speed = 115200